import { ReactNode } from 'react'

import { locales } from '@/common/constants/locales'
import { roboto, russoOne } from '@/styles/fonts'
import clsx from 'clsx'
import { Metadata } from 'next'

export async function generateStaticParams() {
  return locales.map(locale => {
    locale
  })
  //return [{ lang: 'en' }, { lang: 'de' }, { lang: 'cn' }]
}

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Portfolio | Dmitry Shamko',
}

type Props = {
  children: ReactNode
  params: { locale: string }
}

export default async function RootLayout({ children, params: { locale } }: Props) {
  const classNames = {
    body: clsx(roboto.variable, russoOne.variable),
  }

  return (
    <html className={classNames.body} lang={locale}>
      <body>{children}</body>
    </html>
  )
}
